name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test, Lint & Format Check
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install system fonts for consistent rendering
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-liberation fonts-dejavu-core

      - name: Run unit tests
        run: npm test

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Run component tests
        run: npm run test:ct

      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 30

      - name: Run lint and format check
        run: npx biome ci
