name: Add Copilot Reviewer

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-copilot-reviewer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Add Copilot as reviewer
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer github/copilot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
